### ISSUE TITLE
Document usage with testOnly

### ISSUE THREAD

**Issue by joprice** [localytics/sbt-dynamodb#12]
Is there a way to connect the start/stop tasks with testOnly? doFinally seems to not work well with inputTasks.

**Comment by bdarfler** [comment]
Hey @joprice, this is testing the limits of my sbt understanding. In the mean time I would suggest just using 

`start-dynamodb-local` and `stop-dynamodb-local` directly in `sbt`

You'll have the added benefit of not having to wait for dynamodb-local to start up for each test run.

**Comment by joprice** [comment]
I ended up only adding start, and manually stopping before closing sbt. Maybe a shutdown hook could be used to clean it up on exit?

**Comment by bdarfler** [comment]
Sounds like a good work around for now. I've tried a number of different options at this point and none of the easy ones (i.e. just changing sbt configuration, not restructuring sbt-dynamodb code) seem to work. I have an idea that I'll work on later that requires restructuring some sbt-dynamodb code but that will have to wait until after NEScala.
