### ISSUE TITLE
Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by joprice** [localytics/sbt-dynamodb#13]
[info] Extracting file: [ .../target/dynamodb-local/dynamodb_local_latest.tar.gz]
DynamoDBLocal.jar: (Empty error message)
tar: Error exit delayed from previous errors.
[info] Starting dynamodb local
[info] Waiting for dynamodb local to boot on port 8000
Error: Invalid or corrupt jarfile

**Comment by bdarfler** [comment]
Hmm, can you give some context @joprice? Does this happen constantly? If you clear the jar and redownload does it resolve the issue?

**Comment by joprice** [comment]
Sorry for the lack of details. I created the issue in a rush so that I wouldn't forget. Here's some context: My tests were hanging after outputting that dynamodb-local was downloaded. I eventually killed the process. After that, I got this error until I cleaned, then the hanging again. After checking the size of the file, I found that it was simply downloading very slowly for whatever reason. Updating the output to indicate progress would save others' time debugging.

**Comment by bdarfler** [comment]
Interesting. Unfortunately SBT doesn't appear to support [showing download progress](http://stackoverflow.com/questions/19527213/sbt-io-download-method-show-progress) out of the box and I'd rather not bring in a dependency just for this. 

I looked back at the code and there is a [log line](https://github.com/localytics/sbt-dynamodb/blob/master/src/main/scala/com/localytics/sbt/dynamodb/DynamoDBLocalTasks.scala#L23) before downloading the jar but not after. It sounds like you might have glanced quickly and not noticed that the text said "Downloading" and not "Downloaded".

One thing I do think we could do better at is handling any untar/zip failure. I'll see about improving that.

**Comment by joprice** [comment]
I did notice it said 'Downloading', but immediately after, it printed Scalacheck output, which gave me the impression that the test runner had started, but was hanging. I know sbt runs things concurrently and I assume the ordering here is not something under in the plugin's control.

```
[info] Creating DynamoDB Local directory [...]
[info] Downloading DynamoDB Local from [http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_2016-03-01.tar.gz] to [...dynamodb-local/dynamodb_local_2016-03-01.tar.gz]
[info] ScalaCheck
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] Extracting file: [.../target/dynamodb-local/dynamodb_local_2016-03-01.tar.gz]
[info] Starting dynamodb local
```

**Comment by bdarfler** [comment]
Interesting. Yah, sbt timing is kind of a mythical beast. The config in the README should ensure that DDBLocal is running before tests start but beyond that its black magic.
