### ISSUE TITLE
Can't find PID to kill with 1.5.0

### ISSUE THREAD

**Issue by philwills** [localytics/sbt-dynamodb#26]
I just tried upgrading from 1.4.1 to 1.5.0 and it consistently fails to find the PID to kill the process after tests have completed. Reverting to 1.4.1 fixes the problem. I'm running on OSX.

I assume this related to #25.

**Comment by bdarfler** [comment]
Check out 1.5.1, thanks for the report and sorry for the bother.

**Comment by philwills** [comment]
That seems to have fixed it. Thanks very much.
