### ISSUE TITLE
Separate settings for Test and Compile?

### ISSUE THREAD

**Issue by bleshik** [localytics/sbt-dynamodb#33]
I'd like to start dynamodb not only for tests but for "sbt run" as well, so that I don't need to start it separately every time.
I was able to setup the starting of dynamodb with no problems, but I'd like to use in-memory mode only for tests.
I tried several ways of overriding the settings, but with no luck. For example:  
dynamoDBLocalInMemory in Compile := false
dynamoDBLocalDBPath in Test := None
dynamoDBLocalPort in Test := 8001
This will still use the default settings.

I will deeply appreciate any guidance on that. Thanks!

**Comment by bdarfler** [comment]
Hi @bleshik, I believe you are correct that the plugin does not respect configuration scopes for the settings. I think I understand how to correct this based on http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html#Provide+raw+settings+and+configured+settings. Let me see if I can get to this over the next few days.

**Comment by bdarfler** [comment]
@bleshik should be good to go, let me know if you run into any issues.
