### ISSUE TITLE
question: is there a create-table setting?

### ISSUE THREAD

**Issue by timgifford** [localytics/sbt-dynamodb#36]
I've started playing around with this plugin. I noticed the maven plugin has a goal that would create the dynamo tables. I was curious if there is similar functionality with this plugin. If not, is there some guidance on when to create the tables?

**Comment by bdarfler** [comment]
Hi @timgifford. There isn't a setting like that with this plugin ( though PRs are always welcome ;-) ). I would recommend putting the create table logic where ever you instantiate your DynamoDB connection. Additionally, you will want to check that the table exists (via a DescribeTable call) before creating it (via a CreateTable call) or handle the Exception that is returned when the table already exists, I believe that is a `ResourceInUseException`.

**Comment by timgifford** [comment]
Thanks. I'll close this issue and setup tables during in the test executions.
