### ISSUE TITLE
TestOnly scope not working

### ISSUE THREAD

**Issue by nterry** [localytics/sbt-dynamodb#40]
So I followed the README and 'sbt test' works great. But when I run sbt "test:testOnly *Whatever", I get the following:

    [error] Expected key
    [error] Expected '::'
    [error] Expected end of input.
    [error] test:testOnly *Whatever
    [error]

The command works when I comment out the 'testOnly in Test := (testOnly in Test).dependsOn(startDynamoDBLocal).value' line from build.sbt

**Comment by rvangsgaard** [comment]
Using `.evaluated` instead of `.value`, fixes this for me:
```
startDynamoDBLocal := startDynamoDBLocal.dependsOn(compile in Test).value
test in Test := (test in Test).dependsOn(startDynamoDBLocal).value
testOnly in Test := (testOnly in Test).dependsOn(startDynamoDBLocal).evaluated
testOptions in Test += dynamoDBLocalTestCleanup.value
```

Source: https://github.com/localytics/sbt-sqs/pull/9/commits/01c26e658a42a2d125b0f97f936746aafbf07c42

**Comment by jsolmon** [comment]
I've updated the README to fix the instructions for `testOnly`. Thanks for bringing up the issue.
